### ISSUE TITLE
Como saberei quem fez o site e em que ano ele foi feito?

### ISSUE THREAD

**Issue by mondini** [marcelopottier/marcelopottier.github.io#1]
Sugiro colocar no rodapé do site, pra manter a pegada:
Desenvolvido por Marcelão da Massa® - Todos os direitos reservados - 2006

**Comment by marcelopottier** [comment]
Feito! A minha ideia é reutilizar esse mesmo modelo nos próximos trabalhos de WEB por isso não me atentei muito aos detalhes.
